### ISSUE TITLE
3090 24g爆显存了，，

### ISSUE THREAD

**Issue by testmurk** [thinksoso/ChatGLM-Instruct-Tuning#1]
--per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --train_file ./data/train.txt \
    --validation_file ./data/valid.txt \
    --max_seq_length 256 \

减小了batch_size 还是不行QAQ

**Comment by s65b40** [comment]
根据经验，单卡推理大概需要25400+MB的显存，，，
