### ISSUE TITLE
训练时显存不足

### ISSUE THREAD

**Issue by RigelA** [thinksoso/ChatGLM-Instruct-Tuning#4]
请问你们在训练时用什么显卡训练的，我用A100 40G会爆显存

**Comment by thinksoso** [comment]
batch_size调到64试试

**Comment by RigelA** [comment]
max_seq_length改为64，batch size改为1都不行

**Comment by thinksoso** [comment]
我们用A100-80G训的，参考这个[项目]( https://github.com/SCIR-HI/Med-ChatGLM)，如果还不行可以考虑用官方开源的[p tuning](https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning) 方式训练

**Comment by RigelA** [comment]
多谢，我看下，p tuning试过，很难收敛

**Comment by RigelA** [comment]
这里再补充下，内存不足，可以用deepspeed，在命令行参数里指定deepspeed配置文件即可
